services:
  # The Postgres Database Service
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    networks:
      - pg-shared-network

  # The pgAdmin Management Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - pg-shared-network
    depends_on:
      - pgdatabase

  # The Data Ingestion Service
  # ingest_data:
  #   image: zone_ingest:v001
  #   container_name: ingest_data
  #   networks:
  #     - pg-shared-net
  #   depends_on:
  #     - pgdatabase
  #   command:
  #     - --pg-user=root
  #     - --pg-pw=root
  #     - --pg-host=pgdatabase
  #     - --pg-port=5432
  #     - --pg-db=ny_taxi
  #     - --target-table=taxi_zone_data
  #     - --year=2021
  #     - --month=1
  #     - --chunksize=100000

# Define the shared network and persistent volumes
networks:
  pg-shared-network:
    driver: bridge

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: